export const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWYZ'.split('');
export interface Location {
  name: string;
  postcode: string;
  region: string;
  lat?: string;
  lng?: string;
}
export const regions = [
  { name: 'Sydney CBD' },
  { name: 'Sydney Inner West' },
  { name: 'Sydney Western Suburbs' },
  { name: 'Sydney Sutherland Shire' },
  { name: 'Sydney Eastern Suburbs' },
  { name: 'Northwest Sydney' },
  { name: 'Sydney Northern Beaches' },
  { name: 'Sydney North Shore' },
];

export const locations = [
  // A
  { name: 'Alexandria NSW', postcode: '2015', region: 'Sydney Eastern Suburbs', lat: '-33.9100', lng: '151.1960' },
  { name: 'Annandale NSW', postcode: '2038', region: 'Sydney Inner West', lat: '-33.8847', lng: '151.1694' },
  { name: 'Arncliffe NSW', postcode: '2205', region: 'Sydney Inner West', lat: '-33.9353', lng: '151.1469' },
  { name: 'Arndell Park NSW', postcode: '2148', region: 'Sydney Western Suburbs', lat: '-33.7697', lng: '150.8667' },
  { name: 'Artarmon NSW', postcode: '2064', region: 'Northwest Sydney', lat: '-33.8147', lng: '151.1803' },
  { name: 'Ashfield NSW', postcode: '2131', region: 'Sydney Inner West', lat: '-33.8886', lng: '151.1243' },
  { name: 'Auburn NSW', postcode: '2144', region: 'Sydney Western Suburbs', lat: '-33.8497', lng: '151.0326' },
  { name: 'Avalon NSW', postcode: '2107', region: 'Northwest Sydney', lat: '-33.6333', lng: '151.3333' },
  // B
  {
    name: 'Badgerys Creek NSW',
    postcode: '2555',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Balgowlah NSW', postcode: '2093', region: 'Northwest Sydney' },
  { name: 'Balmain NSW', postcode: '2041', region: 'Sydney Inner West' },
  {
    name: 'Banksmeadow NSW',
    postcode: '2019',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Bankstown NSW', postcode: '2200', region: 'Sydney Western Suburbs' },
  {
    name: 'Barangaroo NSW',
    postcode: '2000',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Bardwell Park NSW', postcode: '2207', region: 'Sydney Inner West' },
  { name: 'Bass Hill NSW', postcode: '2197', region: 'Sydney Western Suburbs' },
  { name: 'Baulkham Hills NSW', postcode: '2153', region: 'Northwest Sydney' },
  { name: 'Bayview NSW', postcode: '2104', region: 'Northwest Sydney' },
  {
    name: 'Beaconsfield NSW',
    postcode: '2015',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Beecroft NSW', postcode: '2119', region: 'Northwest Sydney' },
  { name: 'Belfield NSW', postcode: '2191', region: 'Sydney Inner West' },
  { name: 'Bella Vista NSW', postcode: '2153', region: 'Northwest Sydney' },
  {
    name: 'Bellevue Hill NSW',
    postcode: '2023',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Belmore NSW', postcode: '2192', region: 'Sydney Inner West' },
  { name: 'Belrose NSW', postcode: '2085', region: 'Northwest Sydney' },
  { name: 'Berala NSW', postcode: '2141', region: 'Sydney Western Suburbs' },
  { name: 'Berowra Waters NSW', postcode: '2082', region: 'Northwest Sydney' },
  { name: 'Beverly Hills NSW', postcode: '2209', region: 'Sydney Inner West' },
  { name: 'Bexley NSW', postcode: '2207', region: 'Sydney Inner West' },
  { name: 'Blacktown NSW', postcode: '2140', region: 'Sydney Western Suburbs' },
  {
    name: 'Blakehurst NSW',
    postcode: '2221',
    region: 'Sydney Sutherland Shire',
  },
  { name: 'Bondi NSW', postcode: '2026', region: 'Sydney Eastern Suburbs' },
  {
    name: 'Bondi Junction NSW',
    postcode: '2022',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Bonnyrigg NSW', postcode: '2177', region: 'Sydney Western Suburbs' },
  {
    name: 'Bossley Park NSW',
    postcode: '2176',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Botany NSW', postcode: '2019', region: 'Sydney Eastern Suburbs' },
  { name: 'Box Hill NSW', postcode: '2765', region: 'Northwest Sydney' },
  {
    name: 'Breakfast Point NSW',
    postcode: '2137',
    region: 'Sydney Inner West',
  },
  {
    name: 'Brighton-Le-Sands NSW',
    postcode: '2216',
    region: 'Sydney Inner West',
  },
  { name: 'Bronte NSW', postcode: '2024', region: 'Sydney Eastern Suburbs' },
  { name: 'Brookvale NSW', postcode: '2075', region: 'Northwest Sydney' },
  { name: 'Burwood NSW', postcode: '2134', region: 'Sydney Inner West' },
  // C
  { name: 'Cabarita NSW', postcode: '2137', region: 'Sydney Inner West' },
  {
    name: 'Cabramatta West NSW',
    postcode: '2166',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Camden NSW', postcode: '2570', region: 'Sydney Western Suburbs' },
  { name: 'Camellia NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Cammeray NSW', postcode: '2062', region: 'Northwest Sydney' },
  {
    name: 'Campbelltown NSW',
    postcode: '2560',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Campsie NSW', postcode: '2194', region: 'Sydney Inner West' },
  { name: 'Camperdown NSW', postcode: '2050', region: 'Sydney Inner West' },
  { name: 'Canada Bay NSW', postcode: '2046', region: 'Sydney Inner West' },
  {
    name: 'Canley Vale NSW',
    postcode: '2166',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Canterbury NSW', postcode: '2193', region: 'Sydney Inner West' },
  {
    name: 'Caringbah NSW',
    postcode: '2229',
    region: 'Sydney Sutherland Shire',
  },
  { name: 'Carlingford NSW', postcode: '2118', region: 'Northwest Sydney' },
  { name: 'Carlton NSW', postcode: '2218', region: 'Sydney Inner West' },
  { name: 'Carramar NSW', postcode: '2163', region: 'Sydney Western Suburbs' },
  { name: 'Castle Hill NSW', postcode: '2154', region: 'Northwest Sydney' },
  {
    name: 'Castlereagh NSW',
    postcode: '2749',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Chatswood NSW', postcode: '2067', region: 'Northwest Sydney' },
  { name: 'Cherrybrook NSW', postcode: '2126', region: 'Northwest Sydney' },
  {
    name: 'Chester Hill NSW',
    postcode: '2162',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Chinatown NSW', postcode: '2000', region: 'Sydney Eastern Suburbs' },
  { name: 'Chippendale NSW', postcode: '2008', region: 'Sydney Inner West' },
  {
    name: 'Chipping Norton NSW',
    postcode: '2170',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Chullora NSW', postcode: '2190', region: 'Sydney Western Suburbs' },
  {
    name: 'Circular Quay NSW',
    postcode: '2000',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Clovelly NSW', postcode: '2031', region: 'Sydney Eastern Suburbs' },
  { name: 'Clyde NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Collaroy NSW', postcode: '2097', region: 'Northwest Sydney' },
  { name: 'Concord NSW', postcode: '2137', region: 'Sydney Inner West' },
  {
    name: 'Condell Park NSW',
    postcode: '2200',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Coogee NSW', postcode: '2034', region: 'Sydney Eastern Suburbs' },
  { name: 'Cremorne NSW', postcode: '2090', region: 'Northwest Sydney' },
  { name: 'Cronulla NSW', postcode: '2230', region: 'Sydney Sutherland Shire' },
  { name: 'Crows Nest NSW', postcode: '2065', region: 'Northwest Sydney' },
  { name: 'Croydon NSW', postcode: '2132', region: 'Sydney Inner West' },
  { name: 'Croydon Park NSW', postcode: '2133', region: 'Sydney Inner West' },
  // D
  {
    name: 'Darling Harbour NSW',
    postcode: '2000',
    region: 'Sydney Eastern Suburbs',
  },
  {
    name: 'Darlinghurst NSW',
    postcode: '2010',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Dee Why NSW', postcode: '2099', region: 'Northwest Sydney' },
  {
    name: 'Double Bay NSW',
    postcode: '2028',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Drummoyne NSW', postcode: '2047', region: 'Sydney Inner West' },
  { name: 'Dulwich Hill NSW', postcode: '2203', region: 'Sydney Inner West' },
  { name: 'Dural NSW', postcode: '2158', region: 'Northwest Sydney' },
  // E
  { name: 'Earlwood NSW', postcode: '2206', region: 'Sydney Inner West' },
  {
    name: 'East Hills NSW',
    postcode: '2213',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Eastern Creek NSW',
    postcode: '2766',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Eastwood NSW', postcode: '2122', region: 'Northwest Sydney' },
  {
    name: 'Edensor Park NSW',
    postcode: '2176',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Edgecliff NSW', postcode: '2027', region: 'Sydney Eastern Suburbs' },
  {
    name: 'Emu Plains NSW',
    postcode: '2750',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Enfield NSW', postcode: '2136', region: 'Sydney Inner West' },
  { name: 'Engadine NSW', postcode: '2233', region: 'Sydney Sutherland Shire' },
  { name: 'Enmore NSW', postcode: '2042', region: 'Sydney Inner West' },
  { name: 'Epping NSW', postcode: '2121', region: 'Northwest Sydney' },
  { name: 'Ermington NSW', postcode: '2115', region: 'Northwest Sydney' },
  {
    name: 'Erskine Park NSW',
    postcode: '2759',
    region: 'Sydney Western Suburbs',
  },
  // F
  { name: 'Fairfield NSW', postcode: '2165', region: 'Sydney Western Suburbs' },
  { name: 'Five Dock NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Forestville NSW', postcode: '2087', region: 'Northwest Sydney' },
  { name: 'Frenchs Forest NSW', postcode: '2086', region: 'Northwest Sydney' },
  // G
  { name: 'Galston NSW', postcode: '2159', region: 'Northwest Sydney' },
  { name: 'Girraween NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Gladesville NSW', postcode: '2111', region: 'Sydney Inner West' },
  { name: 'Glebe NSW', postcode: '2037', region: 'Sydney Inner West' },
  {
    name: 'Glendenning NSW',
    postcode: '2761',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Glenorie NSW', postcode: '2157', region: 'Northwest Sydney' },
  { name: 'Glenwood NSW', postcode: '2768', region: 'Northwest Sydney' },
  { name: 'Gordon NSW', postcode: '2072', region: 'Northwest Sydney' },
  { name: 'Granville NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Greenacre NSW', postcode: '2190', region: 'Sydney Western Suburbs' },
  { name: 'Guildford NSW', postcode: '2161', region: 'Sydney Western Suburbs' },
  { name: 'Gymea NSW', postcode: '2227', region: 'Sydney Sutherland Shire' },
  // H
  { name: 'Haberfield NSW', postcode: '2045', region: 'Sydney Inner West' },
  { name: 'Harbord NSW', postcode: '2096', region: 'Northwest Sydney' },
  {
    name: 'Harris Park NSW',
    postcode: '2150',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Heathcote NSW',
    postcode: '2233',
    region: 'Sydney Sutherland Shire',
  },
  { name: 'Homebush Bay NSW', postcode: '2127', region: 'Sydney Inner West' },
  { name: 'Homebush NSW', postcode: '2140', region: 'Sydney Inner West' },
  { name: 'Hornsby NSW', postcode: '2077', region: 'Northwest Sydney' },
  {
    name: 'Horsley Park NSW',
    postcode: '2175',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Hoxton Park NSW',
    postcode: '2171',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Hunters Hill NSW', postcode: '2110', region: 'Sydney Inner West' },
  {
    name: 'Huntingwood NSW',
    postcode: '2148',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Hurstville NSW',
    postcode: '2220',
    region: 'Sydney Sutherland Shire',
  },
  // I
  { name: 'Ingleside NSW', postcode: '2101', region: 'Northwest Sydney' },
  { name: 'Ingleburn NSW', postcode: '2565', region: 'Sydney Western Suburbs' },
  // J
  {
    name: 'Jamisontown NSW',
    postcode: '2750',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Jannali NSW', postcode: '2226', region: 'Sydney Sutherland Shire' },
  // K
  { name: 'Kellyville NSW', postcode: '2155', region: 'Northwest Sydney' },
  {
    name: 'Kensington NSW',
    postcode: '2033',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Kenthurst NSW', postcode: '2156', region: 'Northwest Sydney' },
  { name: 'Killara NSW', postcode: '2071', region: 'Northwest Sydney' },
  {
    name: 'Kings Cross NSW',
    postcode: '2011',
    region: 'Sydney Eastern Suburbs',
  },
  {
    name: 'Kings Park NSW',
    postcode: '2148',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Kingsford NSW', postcode: '2032', region: 'Sydney Eastern Suburbs' },
  { name: 'Kingsgrove NSW', postcode: '2208', region: 'Sydney Inner West' },
  { name: 'Kingswood NSW', postcode: '2747', region: 'Sydney Western Suburbs' },
  { name: 'Kogarah NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Kurnell NSW', postcode: '2231', region: 'Sydney Sutherland Shire' },
  // L
  { name: 'Lakemba NSW', postcode: '2195', region: 'Sydney Inner West' },
  { name: 'Lane Cove NSW', postcode: '2066', region: 'Northwest Sydney' },
  { name: 'Lansvale NSW', postcode: '2166', region: 'Sydney Western Suburbs' },
  { name: 'Leichhardt NSW', postcode: '2040', region: 'Sydney Inner West' },
  { name: 'Lidcombe NSW', postcode: '2141', region: 'Sydney Western Suburbs' },
  { name: 'Lilyfield NSW', postcode: '2040', region: 'Sydney Inner West' },
  { name: 'Lindfield NSW', postcode: '2070', region: 'Northwest Sydney' },
  { name: 'Liverpool NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  // M
  { name: 'Macquarie Park NSW', postcode: '2113', region: 'Northwest Sydney' },
  { name: 'Marrickville NSW', postcode: '2204', region: 'Sydney Inner West' },
  { name: 'Mascot NSW', postcode: '2020', region: 'Sydney Eastern Suburbs' },
  {
    name: 'Matraville NSW',
    postcode: '2036',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'McMahons Point NSW', postcode: '2060', region: 'Northwest Sydney' },
  { name: 'Meadowbank NSW', postcode: '2114', region: 'Northwest Sydney' },
  { name: 'Menai NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  {
    name: 'Merrylands NSW',
    postcode: '2160',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Milperra NSW', postcode: '2214', region: 'Sydney Western Suburbs' },
  { name: 'Milsons Point NSW', postcode: '2061', region: 'Northwest Sydney' },
  {
    name: 'Minchinbury NSW',
    postcode: '2770',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Minto NSW', postcode: '2566', region: 'Sydney Western Suburbs' },
  { name: 'Miranda NSW', postcode: '2228', region: 'Sydney Sutherland Shire' },
  {
    name: 'Moore Park NSW',
    postcode: '2021',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Moorebank NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Mortdale NSW', postcode: '2223', region: 'Sydney Sutherland Shire' },
  { name: 'Mosman NSW', postcode: '2088', region: 'Northwest Sydney' },
  { name: 'Mount Colah NSW', postcode: '2079', region: 'Northwest Sydney' },
  {
    name: 'Mount Druitt NSW',
    postcode: '2770',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Mount Kuring-gai NSW',
    postcode: '2080',
    region: 'Northwest Sydney',
  },
  { name: 'Mulgoa NSW', postcode: '2745', region: 'Sydney Western Suburbs' },
  // N
  { name: 'Narellan NSW', postcode: '2567', region: 'Sydney Western Suburbs' },
  { name: 'Narrabeen NSW', postcode: '2101', region: 'Northwest Sydney' },
  { name: 'Neutral Bay NSW', postcode: '2089', region: 'Northwest Sydney' },
  { name: 'Newington NSW', postcode: '2127', region: 'Sydney Inner West' },
  { name: 'Newport NSW', postcode: '2106', region: 'Northwest Sydney' },
  { name: 'Newtown NSW', postcode: '2042', region: 'Sydney Inner West' },
  {
    name: 'North Parramatta NSW',
    postcode: '2151',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'North Richmond NSW',
    postcode: '2754',
    region: 'Sydney Western Suburbs',
  },
  { name: 'North Rocks NSW', postcode: '2151', region: 'Northwest Sydney' },
  { name: 'North Ryde NSW', postcode: '2113', region: 'Northwest Sydney' },
  { name: 'North Sydney NSW', postcode: '2060', region: 'Northwest Sydney' },
  { name: 'Northbridge NSW', postcode: '2063', region: 'Northwest Sydney' },
  { name: 'Northmead NSW', postcode: '2152', region: 'Sydney Western Suburbs' },
  { name: 'Norwest NSW', postcode: '2153', region: 'Northwest Sydney' },
  // O
  { name: 'Oatlands NSW', postcode: '2117', region: 'Northwest Sydney' },
  { name: 'Oakhurst NSW', postcode: '2761', region: 'Sydney Western Suburbs' },
  {
    name: 'Oyster Bay NSW',
    postcode: '2225',
    region: 'Sydney Sutherland Shire',
  },
  // P
  {
    name: 'Paddington NSW',
    postcode: '2021',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Padstow NSW', postcode: '2211', region: 'Sydney Western Suburbs' },
  { name: 'Pagewood NSW', postcode: '2035', region: 'Sydney Eastern Suburbs' },
  { name: 'Parklea NSW', postcode: '2768', region: 'Northwest Sydney' },
  {
    name: 'Parramatta NSW',
    postcode: '2150',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Peakhurst NSW',
    postcode: '2210',
    region: 'Sydney Sutherland Shire',
  },
  {
    name: 'Pendle Hill NSW',
    postcode: '2145',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Pennant Hills NSW', postcode: '2120', region: 'Northwest Sydney' },
  { name: 'Penrith NSW', postcode: '2750', region: 'Sydney Western Suburbs' },
  {
    name: 'Penshurst NSW',
    postcode: '2222',
    region: 'Sydney Sutherland Shire',
  },
  { name: 'Petersham NSW', postcode: '2049', region: 'Sydney Inner West' },
  {
    name: 'Potts Point NSW',
    postcode: '2011',
    region: 'Sydney Eastern Suburbs',
  },
  { name: 'Prestons NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Prospect NSW', postcode: '2148', region: 'Sydney Western Suburbs' },
  { name: 'Pyrmont NSW', postcode: '2009', region: 'Sydney Inner West' },
  // R
  { name: 'Randwick NSW', postcode: '2031', region: 'Sydney Eastern Suburbs' },
  { name: 'Redfern NSW', postcode: '2016', region: 'Sydney Inner West' },
  { name: 'Revesby NSW', postcode: '2212', region: 'Sydney Western Suburbs' },
  { name: 'Rhodes NSW', postcode: '2138', region: 'Sydney Inner West' },
  { name: 'Rose Bay NSW', postcode: '2029', region: 'Sydney Eastern Suburbs' },
  { name: 'Rosebery NSW', postcode: '2018', region: 'Sydney Eastern Suburbs' },
  { name: 'Roseville NSW', postcode: '2069', region: 'Northwest Sydney' },
  { name: 'Rouse Hill NSW', postcode: '2155', region: 'Northwest Sydney' },
  { name: 'Rozelle NSW', postcode: '2039', region: 'Sydney Inner West' },
  { name: 'Rydalmere NSW', postcode: '2116', region: 'Sydney Western Suburbs' },
  { name: 'Ryde NSW', postcode: '2112', region: 'Northwest Sydney' },
  // S
  {
    name: 'Seven Hills NSW',
    postcode: '2147',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Silverwater NSW',
    postcode: '2128',
    region: 'Sydney Western Suburbs',
  },
  {
    name: 'Smithfield NSW',
    postcode: '2164',
    region: 'Sydney Western Suburbs',
  },
  { name: 'St Marys NSW', postcode: '2760', region: 'Sydney Western Suburbs' },
  { name: 'St Peters NSW', postcode: '2044', region: 'Sydney Inner West' },
  { name: 'St. Leonards NSW', postcode: '2065', region: 'Northwest Sydney' },
  { name: 'Strathfield NSW', postcode: '2135', region: 'Sydney Inner West' },
  {
    name: 'Surry Hills NSW',
    postcode: '2010',
    region: 'Sydney Eastern Suburbs',
  },
  {
    name: 'Sydney Olympic Park NSW',
    postcode: '2127',
    region: 'Sydney Inner West',
  },
  // T
  {
    name: 'Toongabbie NSW',
    postcode: '2146',
    region: 'Sydney Western Suburbs',
  },
  // U
  { name: 'Ultimo NSW', postcode: '2007', region: 'Sydney Inner West' },
  // V
  { name: 'Villawood NSW', postcode: '2163', region: 'Sydney Western Suburbs' },
  // W
  {
    name: 'Warwick Farm NSW',
    postcode: '2170',
    region: 'Sydney Western Suburbs',
  },
  { name: 'Waterloo NSW', postcode: '2017', region: 'Sydney Eastern Suburbs' },
  { name: 'Waverley NSW', postcode: '2024', region: 'Sydney Eastern Suburbs' },
  { name: 'Waverton NSW', postcode: '2060', region: 'Northwest Sydney' },
  { name: 'Westmead NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Willoughby NSW', postcode: '2068', region: 'Northwest Sydney' },
  { name: 'Wolli Creek NSW', postcode: '2205', region: 'Sydney Inner West' },
  { name: 'Woollahra NSW', postcode: '2025', region: 'Sydney Eastern Suburbs' },
  {
    name: 'Woolloomooloo NSW',
    postcode: '2011',
    region: 'Sydney Eastern Suburbs',
  },
  // Y
  { name: 'Yagoona NSW', postcode: '2199', region: 'Sydney Western Suburbs' },
  { name: 'Yennora NSW', postcode: '2161', region: 'Sydney Western Suburbs' },
  // Z
  { name: 'Zetland NSW', postcode: '2017', region: 'Sydney Eastern Suburbs' },

  // Additional suburbs from locations.md
  { name: 'Abbotsbury NSW', postcode: '2176', region: 'Sydney Western Suburbs' },
  { name: 'Abbotsford NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Acacia Gardens NSW', postcode: '2763', region: 'Northwest Sydney' },
  { name: 'Alfords Point NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Allambie Heights NSW', postcode: '2100', region: 'Sydney Northern Beaches' },
  { name: 'Allawah NSW', postcode: '2218', region: 'Sydney Sutherland Shire' },
  { name: 'Annangrove NSW', postcode: '2156', region: 'Northwest Sydney' },
  { name: 'Arcadia NSW', postcode: '2159', region: 'Northwest Sydney' },
  { name: 'Ashbury NSW', postcode: '2193', region: 'Sydney Inner West' },
  { name: 'Ashcroft NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Asquith NSW', postcode: '2077', region: 'Sydney North Shore' },
  { name: 'Audley NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Austral NSW', postcode: '2179', region: 'Sydney Western Suburbs' },
  { name: 'Australia Square NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Balgowlah Heights NSW', postcode: '2093', region: 'Sydney Northern Beaches' },
  { name: 'Balmain East NSW', postcode: '2041', region: 'Sydney Inner West' },
  { name: 'Bangor NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Banksia NSW', postcode: '2216', region: 'Sydney Sutherland Shire' },
  { name: 'Bankstown Aerodrome NSW', postcode: '2200', region: 'Sydney Western Suburbs' },
  { name: 'Bankstown North NSW', postcode: '2200', region: 'Sydney Western Suburbs' },
  { name: 'Bankstown Square NSW', postcode: '2200', region: 'Sydney Western Suburbs' },
  { name: 'Bar Point NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Barden Ridge NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Bardwell Valley NSW', postcode: '2207', region: 'Sydney Sutherland Shire' },
  { name: 'Beacon Hill NSW', postcode: '2100', region: 'Sydney Northern Beaches' },
  { name: 'Beaumont Hills NSW', postcode: '2155', region: 'Northwest Sydney' },
  { name: 'Belrose West NSW', postcode: '2085', region: 'Sydney Northern Beaches' },
  { name: 'Berowra NSW', postcode: '2081', region: 'Sydney North Shore' },
  { name: 'Berowra Heights NSW', postcode: '2082', region: 'Sydney North Shore' },
  { name: 'Berrilee NSW', postcode: '2159', region: 'Northwest Sydney' },
  { name: 'Beverley Park NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Bexley North NSW', postcode: '2207', region: 'Sydney Sutherland Shire' },
  { name: 'Bexley South NSW', postcode: '2207', region: 'Sydney Sutherland Shire' },
  { name: 'Bidwill NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Bilgola NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Birchgrove NSW', postcode: '2041', region: 'Sydney Inner West' },
  { name: 'Birrong NSW', postcode: '2143', region: 'Sydney Western Suburbs' },
  { name: 'Blackett NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Blacktown Westpoint NSW', postcode: '2148', region: 'Sydney Western Suburbs' },
  { name: 'Blaxcell NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Blenheim Road NSW', postcode: '2112', region: 'Sydney North Shore' },
  { name: 'Bondi Beach NSW', postcode: '2026', region: 'Sydney Eastern Suburbs' },
  { name: 'Bondi Junction Plaza NSW', postcode: '2022', region: 'Sydney Eastern Suburbs' },
  { name: 'Bonnet Bay NSW', postcode: '2226', region: 'Sydney Sutherland Shire' },
  { name: 'Bonnyrigg Heights NSW', postcode: '2177', region: 'Sydney Western Suburbs' },
  { name: 'Boronia Park NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Bow Bowing NSW', postcode: '2566', region: 'Sydney Western Suburbs' },
  { name: 'Box Head NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Broadway NSW', postcode: '2007', region: 'Sydney CBD' },
  { name: 'Brooklyn NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Bundeena NSW', postcode: '2230', region: 'Sydney Sutherland Shire' },
  { name: 'Burraneer NSW', postcode: '2230', region: 'Sydney Sutherland Shire' },
  { name: 'Burwood Heights NSW', postcode: '2136', region: 'Sydney Inner West' },
  { name: 'Burwood North NSW', postcode: '2134', region: 'Sydney Inner West' },
  { name: 'Busby NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Cabramatta NSW', postcode: '2166', region: 'Sydney Western Suburbs' },
  { name: 'Canley Heights NSW', postcode: '2166', region: 'Sydney Western Suburbs' },
  { name: 'Caravan Head NSW', postcode: '2226', region: 'Sydney Sutherland Shire' },
  { name: 'Careel Bay NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Carlingford Court NSW', postcode: '2118', region: 'Northwest Sydney' },
  { name: 'Carlingford North NSW', postcode: '2118', region: 'Northwest Sydney' },
  { name: 'Carss Park NSW', postcode: '2221', region: 'Sydney Sutherland Shire' },
  { name: 'Cartwright NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Casula NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Casula Mall NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Castle Cove NSW', postcode: '2069', region: 'Sydney North Shore' },
  { name: 'Castlecrag NSW', postcode: '2068', region: 'Sydney North Shore' },
  { name: 'Cecil Hills NSW', postcode: '2171', region: 'Sydney Western Suburbs' },
  { name: 'Cecil Park NSW', postcode: '2178', region: 'Sydney Western Suburbs' },
  { name: 'Cheero Point NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Cheltenham NSW', postcode: '2119', region: 'Northwest Sydney' },
  { name: 'Chifley NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Chiswick NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Church Point NSW', postcode: '2105', region: 'Sydney Northern Beaches' },
  { name: 'Clareville NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Clemton Park NSW', postcode: '2206', region: 'Sydney Inner West' },
  { name: 'Clontarf NSW', postcode: '2093', region: 'Sydney Northern Beaches' },
  { name: 'Clovelly West NSW', postcode: '2031', region: 'Sydney Eastern Suburbs' },
  { name: 'Coasters Retreat NSW', postcode: '2108', region: 'Sydney Northern Beaches' },
  { name: 'Colebee NSW', postcode: '2761', region: 'Northwest Sydney' },
  { name: 'Collaroy Beach NSW', postcode: '2097', region: 'Sydney Northern Beaches' },
  { name: 'Collaroy Plateau West NSW', postcode: '2097', region: 'Sydney Northern Beaches' },
  { name: 'Colyton NSW', postcode: '2760', region: 'Sydney Western Suburbs' },
  { name: 'Como NSW', postcode: '2226', region: 'Sydney Sutherland Shire' },
  { name: 'Concord Repatriation Hospital NSW', postcode: '2139', region: 'Sydney Inner West' },
  { name: 'Concord West NSW', postcode: '2138', region: 'Sydney Inner West' },
  { name: 'Connells Point NSW', postcode: '2221', region: 'Sydney Sutherland Shire' },
  { name: 'Cottage Point NSW', postcode: '2084', region: 'Sydney North Shore' },
  { name: 'Cowan NSW', postcode: '2081', region: 'Sydney North Shore' },
  { name: 'Cromer NSW', postcode: '2099', region: 'Sydney Northern Beaches' },
  { name: 'Curl Curl NSW', postcode: '2096', region: 'Sydney Northern Beaches' },
  { name: 'Currawong Beach NSW', postcode: '2108', region: 'Sydney Northern Beaches' },
  { name: 'Daceyville NSW', postcode: '2032', region: 'Sydney Eastern Suburbs' },
  { name: 'Dangar Island NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Darling Point NSW', postcode: '2027', region: 'Sydney Eastern Suburbs' },
  { name: 'Darlington NSW', postcode: '2008', region: 'Sydney CBD' },
  { name: 'Davidson NSW', postcode: '2085', region: 'Sydney Northern Beaches' },
  { name: 'Dawes Point NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Dean Park NSW', postcode: '2761', region: 'Northwest Sydney' },
  { name: 'Denham Court NSW', postcode: '2565', region: 'Sydney Western Suburbs' },
  { name: 'Denistone NSW', postcode: '2114', region: 'Sydney North Shore' },
  { name: 'Denistone East NSW', postcode: '2112', region: 'Sydney North Shore' },
  { name: 'Denistone West NSW', postcode: '2114', region: 'Sydney North Shore' },
  { name: 'Dharruk NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Dolans Bay NSW', postcode: '2229', region: 'Sydney Sutherland Shire' },
  { name: 'Dolls Point NSW', postcode: '2219', region: 'Sydney Sutherland Shire' },
  { name: 'Doonside NSW', postcode: '2767', region: 'Sydney Western Suburbs' },
  { name: 'Dover Heights NSW', postcode: '2030', region: 'Sydney Eastern Suburbs' },
  { name: 'Duffys Forest NSW', postcode: '2084', region: 'Sydney Northern Beaches' },
  { name: 'Dundas NSW', postcode: '2117', region: 'Northwest Sydney' },
  { name: 'Dundas Valley NSW', postcode: '2117', region: 'Northwest Sydney' },
  { name: 'East Killara NSW', postcode: '2071', region: 'Sydney North Shore' },
  { name: 'East Lindfield NSW', postcode: '2070', region: 'Sydney North Shore' },
  { name: 'East Ryde NSW', postcode: '2113', region: 'Sydney North Shore' },
  { name: 'Eastgardens NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Eastlakes NSW', postcode: '2018', region: 'Sydney Eastern Suburbs' },
  { name: 'Elanora Heights NSW', postcode: '2101', region: 'Sydney Northern Beaches' },
  { name: 'Elizabeth Bay NSW', postcode: '2011', region: 'Sydney Eastern Suburbs' },
  { name: 'Elvina Bay NSW', postcode: '2105', region: 'Sydney Northern Beaches' },
  { name: 'Emerton NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Enfield South NSW', postcode: '2136', region: 'Sydney Inner West' },
  { name: 'Erskineville NSW', postcode: '2043', region: 'Sydney Inner West' },
  { name: 'Eveleigh NSW', postcode: '2015', region: 'Sydney Inner West' },
  { name: 'Fairfield East NSW', postcode: '2165', region: 'Sydney Western Suburbs' },
  { name: 'Fairfield Heights NSW', postcode: '2165', region: 'Sydney Western Suburbs' },
  { name: 'Fairfield West NSW', postcode: '2165', region: 'Sydney Western Suburbs' },
  { name: 'Fairlight NSW', postcode: '2094', region: 'Sydney Northern Beaches' },
  { name: 'Fiddletown NSW', postcode: '2159', region: 'Northwest Sydney' },
  { name: 'Forest Glen NSW', postcode: '2157', region: 'Northwest Sydney' },
  { name: 'Forest Lodge NSW', postcode: '2037', region: 'Sydney Inner West' },
  { name: 'Frenchs Forest East NSW', postcode: '2086', region: 'Sydney Northern Beaches' },
  { name: 'Garie NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Georges Hall NSW', postcode: '2198', region: 'Sydney Western Suburbs' },
  { name: 'Glenhaven NSW', postcode: '2156', region: 'Northwest Sydney' },
  { name: 'Glenfield NSW', postcode: '2167', region: 'Sydney Western Suburbs' },
  { name: 'Glenquarie NSW', postcode: '2564', region: 'Sydney Western Suburbs' },
  { name: 'Grays Point NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Great Mackerel Beach NSW', postcode: '2108', region: 'Sydney Northern Beaches' },
  { name: 'Green Valley NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Greenfield Park NSW', postcode: '2176', region: 'Sydney Western Suburbs' },
  { name: 'Greenwich NSW', postcode: '2065', region: 'Sydney North Shore' },
  { name: 'Grosvenor Place NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Guildford West NSW', postcode: '2161', region: 'Sydney Western Suburbs' },
  { name: 'Hammondville NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Hardys Bay NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Hassall Grove NSW', postcode: '2761', region: 'Northwest Sydney' },
  { name: 'Haymarket NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Hebersham NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Heckenberg NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Henley NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Hillsdale NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Hinchinbrook NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Hmas Kuttabul NSW', postcode: '2011', region: 'Sydney Eastern Suburbs' },
  { name: 'Hmas Rushcutters NSW', postcode: '2027', region: 'Sydney Eastern Suburbs' },
  { name: 'Hmas Waterhen NSW', postcode: '2060', region: 'Sydney North Shore' },
  { name: 'Hmas Watson NSW', postcode: '2030', region: 'Sydney Eastern Suburbs' },
  { name: 'Holroyd NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Holsworthy NSW', postcode: '2173', region: 'Sydney Western Suburbs' },
  { name: 'Homebush South NSW', postcode: '2140', region: 'Sydney Inner West' },
  { name: 'Homebush West NSW', postcode: '2140', region: 'Sydney Inner West' },
  { name: 'Hornsby Heights NSW', postcode: '2077', region: 'Sydney North Shore' },
  { name: 'Horningsea Park NSW', postcode: '2171', region: 'Sydney Western Suburbs' },
  { name: 'Huntleys Cove NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Huntleys Point NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Hurlstone Park NSW', postcode: '2193', region: 'Sydney Inner West' },
  { name: 'Hurstville Grove NSW', postcode: '2220', region: 'Sydney Sutherland Shire' },
  { name: 'Hurstville Westfield NSW', postcode: '2220', region: 'Sydney Sutherland Shire' },
  { name: 'Illawong NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Kangaroo Point NSW', postcode: '2224', region: 'Sydney Sutherland Shire' },
  { name: 'Kareela NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Kellyville Ridge NSW', postcode: '2155', region: 'Northwest Sydney' },
  { name: 'Kemps Creek NSW', postcode: '2178', region: 'Sydney Western Suburbs' },
  { name: 'Killcare NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Killarney Heights NSW', postcode: '2087', region: 'Sydney Northern Beaches' },
  { name: 'Kings Langley NSW', postcode: '2147', region: 'Northwest Sydney' },
  { name: 'Kingsdene NSW', postcode: '2118', region: 'Northwest Sydney' },
  { name: 'Kirrawee NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Kirribilli NSW', postcode: '2061', region: 'Sydney North Shore' },
  { name: 'Kogarah Bay NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Kyeemagh NSW', postcode: '2216', region: 'Sydney Sutherland Shire' },
  { name: 'Kyle Bay NSW', postcode: '2221', region: 'Sydney Sutherland Shire' },
  { name: 'La Perouse NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Lalor Park NSW', postcode: '2147', region: 'Northwest Sydney' },
  { name: 'Lane Cove North NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Lane Cove West NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Lansdowne NSW', postcode: '2163', region: 'Sydney Western Suburbs' },
  { name: 'Lavender Bay NSW', postcode: '2060', region: 'Sydney North Shore' },
  { name: 'Leppington NSW', postcode: '2171', region: 'Sydney Western Suburbs' },
  { name: 'Lewisham NSW', postcode: '2049', region: 'Sydney Inner West' },
  { name: 'Liberty Grove NSW', postcode: '2138', region: 'Sydney Inner West' },
  { name: 'Lidcombe North NSW', postcode: '2141', region: 'Sydney Western Suburbs' },
  { name: 'Lilli Pilli NSW', postcode: '2229', region: 'Sydney Sutherland Shire' },
  { name: 'Lindfield West NSW', postcode: '2070', region: 'Sydney North Shore' },
  { name: 'Linley Point NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Little Bay NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Little Wobby NSW', postcode: '2256', region: 'Sydney Northern Beaches' },
  { name: 'Liverpool South NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Liverpool Westfield NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Loftus NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Long Point NSW', postcode: '2564', region: 'Sydney Western Suburbs' },
  { name: 'Longueville NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Lovett Bay NSW', postcode: '2105', region: 'Sydney Northern Beaches' },
  { name: 'Lucas Heights NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Lugarno NSW', postcode: '2210', region: 'Sydney Sutherland Shire' },
  { name: 'Lurnea NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Macquarie Centre NSW', postcode: '2113', region: 'Sydney North Shore' },
  { name: 'Macquarie Fields NSW', postcode: '2564', region: 'Sydney Western Suburbs' },
  { name: 'Macquarie Links NSW', postcode: '2565', region: 'Sydney Western Suburbs' },
  { name: 'Macquarie University NSW', postcode: '2109', region: 'Sydney North Shore' },
  { name: 'Maianbar NSW', postcode: '2230', region: 'Sydney Sutherland Shire' },
  { name: 'Malabar NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Manly NSW', postcode: '2095', region: 'Sydney Northern Beaches' },
  { name: 'Manly East NSW', postcode: '2095', region: 'Sydney Northern Beaches' },
  { name: 'Manly Vale NSW', postcode: '2093', region: 'Sydney Northern Beaches' },
  { name: 'Marayong NSW', postcode: '2148', region: 'Sydney Western Suburbs' },
  { name: 'Maroubra NSW', postcode: '2035', region: 'Sydney Eastern Suburbs' },
  { name: 'Maroubra South NSW', postcode: '2035', region: 'Sydney Eastern Suburbs' },
  { name: 'Marsden Park NSW', postcode: '2765', region: 'Northwest Sydney' },
  { name: 'Marsfield NSW', postcode: '2122', region: 'Northwest Sydney' },
  { name: 'Mays Hill NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Menai Central NSW', postcode: '2234', region: 'Sydney Sutherland Shire' },
  { name: 'Merrylands West NSW', postcode: '2160', region: 'Sydney Western Suburbs' },
  { name: 'Middle Cove NSW', postcode: '2068', region: 'Sydney North Shore' },
  { name: 'Middle Dural NSW', postcode: '2158', region: 'Northwest Sydney' },
  { name: 'Middleton Grange NSW', postcode: '2171', region: 'Sydney Western Suburbs' },
  { name: 'Millers Point NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Milsons Passage NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Missenden Road NSW', postcode: '2050', region: 'Sydney Inner West' },
  { name: 'Mona Vale NSW', postcode: '2103', region: 'Sydney Northern Beaches' },
  { name: 'Monash Park NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Monterey NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Morning Bay NSW', postcode: '2105', region: 'Sydney Northern Beaches' },
  { name: 'Mortlake NSW', postcode: '2137', region: 'Sydney Inner West' },
  { name: 'Mount Druitt Village NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Mount Lewis NSW', postcode: '2200', region: 'Sydney Western Suburbs' },
  { name: 'Mount Pritchard NSW', postcode: '2170', region: 'Sydney Western Suburbs' },
  { name: 'Mount Vernon NSW', postcode: '2178', region: 'Sydney Western Suburbs' },
  { name: 'Naremburn NSW', postcode: '2065', region: 'Sydney North Shore' },
  { name: 'Narraweena NSW', postcode: '2099', region: 'Sydney Northern Beaches' },
  { name: 'Narwee NSW', postcode: '2209', region: 'Sydney Sutherland Shire' },
  { name: 'Nelson NSW', postcode: '2765', region: 'Northwest Sydney' },
  { name: 'Neutral Bay Junction NSW', postcode: '2089', region: 'Sydney North Shore' },
  { name: 'Newport Beach NSW', postcode: '2106', region: 'Sydney Northern Beaches' },
  { name: 'Normanhurst NSW', postcode: '2076', region: 'Sydney North Shore' },
  { name: 'North Balgowlah NSW', postcode: '2093', region: 'Sydney Northern Beaches' },
  { name: 'North Bondi NSW', postcode: '2026', region: 'Sydney Eastern Suburbs' },
  { name: 'North Curl Curl NSW', postcode: '2099', region: 'Sydney Northern Beaches' },
  { name: 'North Epping NSW', postcode: '2121', region: 'Northwest Sydney' },
  { name: 'North Manly NSW', postcode: '2100', region: 'Sydney Northern Beaches' },
  { name: 'North Narrabeen NSW', postcode: '2101', region: 'Sydney Northern Beaches' },
  { name: 'North Strathfield NSW', postcode: '2137', region: 'Sydney Inner West' },
  { name: 'North Turramurra NSW', postcode: '2074', region: 'Sydney North Shore' },
  { name: 'North Wahroonga NSW', postcode: '2076', region: 'Sydney North Shore' },
  { name: 'North Willoughby NSW', postcode: '2068', region: 'Sydney North Shore' },
  { name: 'Northwood NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Oatley NSW', postcode: '2223', region: 'Sydney Sutherland Shire' },
  { name: 'Old Guildford NSW', postcode: '2161', region: 'Sydney Western Suburbs' },
  { name: 'Old Toongabbie NSW', postcode: '2146', region: 'Sydney Western Suburbs' },
  { name: 'Oxford Falls NSW', postcode: '2100', region: 'Sydney Northern Beaches' },
  { name: 'Oxley Park NSW', postcode: '2760', region: 'Sydney Western Suburbs' },
  { name: 'Padstow Heights NSW', postcode: '2211', region: 'Sydney Sutherland Shire' },
  { name: 'Palm Beach NSW', postcode: '2108', region: 'Sydney Northern Beaches' },
  { name: 'Panania NSW', postcode: '2213', region: 'Sydney Sutherland Shire' },
  { name: 'Paradise Beach NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Parliament House NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Parramatta Westfield NSW', postcode: '2150', region: 'Sydney Western Suburbs' },
  { name: 'Patonga NSW', postcode: '2256', region: 'Sydney Northern Beaches' },
  { name: 'Peakhurst Heights NSW', postcode: '2210', region: 'Sydney Sutherland Shire' },
  { name: 'Pearl Beach NSW', postcode: '2256', region: 'Sydney Northern Beaches' },
  { name: 'Pemulwuy NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Petersham North NSW', postcode: '2049', region: 'Sydney Inner West' },
  { name: 'Phillip Bay NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Picnic Point NSW', postcode: '2213', region: 'Sydney Sutherland Shire' },
  { name: 'Plumpton NSW', postcode: '2761', region: 'Northwest Sydney' },
  { name: 'Pleasure Point NSW', postcode: '2172', region: 'Sydney Sutherland Shire' },
  { name: 'Point Piper NSW', postcode: '2027', region: 'Sydney Eastern Suburbs' },
  { name: 'Port Botany NSW', postcode: '2036', region: 'Sydney Eastern Suburbs' },
  { name: 'Port Hacking NSW', postcode: '2229', region: 'Sydney Sutherland Shire' },
  { name: 'Potts Hill NSW', postcode: '2143', region: 'Sydney Western Suburbs' },
  { name: 'Prairiewood NSW', postcode: '2176', region: 'Sydney Western Suburbs' },
  { name: 'Pretty Beach NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Punchbowl NSW', postcode: '2196', region: 'Sydney Western Suburbs' },
  { name: 'Putney NSW', postcode: '2112', region: 'Sydney North Shore' },
  { name: 'Pymble NSW', postcode: '2073', region: 'Sydney North Shore' },
  { name: 'Quakers Hill NSW', postcode: '2763', region: 'Northwest Sydney' },
  { name: 'Queens Park NSW', postcode: '2022', region: 'Sydney Eastern Suburbs' },
  { name: 'Queen Victoria Building NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Queenscliff NSW', postcode: '2096', region: 'Sydney Northern Beaches' },
  { name: 'Ramsgate NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Ramsgate Beach NSW', postcode: '2217', region: 'Sydney Sutherland Shire' },
  { name: 'Regents Park NSW', postcode: '2143', region: 'Sydney Western Suburbs' },
  { name: 'Revesby Heights NSW', postcode: '2212', region: 'Sydney Sutherland Shire' },
  { name: 'Revesby North NSW', postcode: '2212', region: 'Sydney Sutherland Shire' },
  { name: 'Riverstone NSW', postcode: '2765', region: 'Northwest Sydney' },
  { name: 'Riverwood NSW', postcode: '2210', region: 'Sydney Sutherland Shire' },
  { name: 'Riverview NSW', postcode: '2066', region: 'Sydney North Shore' },
  { name: 'Rockdale NSW', postcode: '2216', region: 'Sydney Sutherland Shire' },
  { name: 'Rodd Point NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Rookwood NSW', postcode: '2141', region: 'Sydney Western Suburbs' },
  { name: 'Rooty Hill NSW', postcode: '2766', region: 'Sydney Western Suburbs' },
  { name: 'Ropes Crossing NSW', postcode: '2760', region: 'Sydney Western Suburbs' },
  { name: 'Rose Bay North NSW', postcode: '2030', region: 'Sydney Eastern Suburbs' },
  { name: 'Rosehill NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'Roselands NSW', postcode: '2196', region: 'Sydney Western Suburbs' },
  { name: 'Roseville Chase NSW', postcode: '2069', region: 'Sydney North Shore' },
  { name: 'Round Corner NSW', postcode: '2158', region: 'Northwest Sydney' },
  { name: 'Royal Exchange NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Royal North Shore Hospital NSW', postcode: '2065', region: 'Sydney North Shore' },
  { name: 'Rushcutters Bay NSW', postcode: '2011', region: 'Sydney Eastern Suburbs' },
  { name: 'Russell Lea NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Sadleir NSW', postcode: '2168', region: 'Sydney Western Suburbs' },
  { name: 'Sandringham NSW', postcode: '2219', region: 'Sydney Sutherland Shire' },
  { name: 'Sandy Point NSW', postcode: '2172', region: 'Sydney Sutherland Shire' },
  { name: 'Sans Souci NSW', postcode: '2219', region: 'Sydney Sutherland Shire' },
  { name: 'Schofields NSW', postcode: '2762', region: 'Northwest Sydney' },
  { name: 'Scotland Island NSW', postcode: '2105', region: 'Sydney Northern Beaches' },
  { name: 'Seaforth NSW', postcode: '2092', region: 'Sydney Northern Beaches' },
  { name: 'Sefton NSW', postcode: '2162', region: 'Sydney Western Suburbs' },
  { name: 'Seven Hills West NSW', postcode: '2147', region: 'Northwest Sydney' },
  { name: 'Shalvey NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Smithfield West NSW', postcode: '2164', region: 'Sydney Western Suburbs' },
  { name: 'South Coogee NSW', postcode: '2034', region: 'Sydney Eastern Suburbs' },
  { name: 'South Granville NSW', postcode: '2142', region: 'Sydney Western Suburbs' },
  { name: 'South Hurstville NSW', postcode: '2221', region: 'Sydney Sutherland Shire' },
  { name: 'South Turramurra NSW', postcode: '2074', region: 'Sydney North Shore' },
  { name: 'South Wentworthville NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Spit Junction NSW', postcode: '2088', region: 'Sydney North Shore' },
  { name: 'St Ives NSW', postcode: '2075', region: 'Sydney North Shore' },
  { name: 'St Ives Chase NSW', postcode: '2075', region: 'Sydney North Shore' },
  { name: 'St Johns Park NSW', postcode: '2176', region: 'Sydney Western Suburbs' },
  { name: 'St Marys East NSW', postcode: '2760', region: 'Sydney Western Suburbs' },
  { name: 'St Pauls NSW', postcode: '2031', region: 'Sydney Eastern Suburbs' },
  { name: 'Stanmore NSW', postcode: '2048', region: 'Sydney Inner West' },
  { name: 'Stanhope Gardens NSW', postcode: '2768', region: 'Northwest Sydney' },
  { name: 'Strathfield South NSW', postcode: '2136', region: 'Sydney Inner West' },
  { name: 'Summer Hill NSW', postcode: '2130', region: 'Sydney Inner West' },
  { name: 'Sutherland NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Sydney Domestic Airport NSW', postcode: '2020', region: 'Sydney CBD' },
  { name: 'Sydney International Airport NSW', postcode: '2020', region: 'Sydney CBD' },
  { name: 'Sydney South NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Sylvania NSW', postcode: '2224', region: 'Sydney Sutherland Shire' },
  { name: 'Sylvania Southgate NSW', postcode: '2224', region: 'Sydney Sutherland Shire' },
  { name: 'Sylvania Waters NSW', postcode: '2224', region: 'Sydney Sutherland Shire' },
  { name: 'Sydenham NSW', postcode: '2044', region: 'Sydney Inner West' },
  { name: 'Tamarama NSW', postcode: '2026', region: 'Sydney Eastern Suburbs' },
  { name: 'Taren Point NSW', postcode: '2229', region: 'Sydney Sutherland Shire' },
  { name: 'Taylors Point NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Telopea NSW', postcode: '2117', region: 'Northwest Sydney' },
  { name: 'Tempe NSW', postcode: '2044', region: 'Sydney Inner West' },
  { name: 'Tennyson Point NSW', postcode: '2111', region: 'Sydney North Shore' },
  { name: 'Terrey Hills NSW', postcode: '2084', region: 'Sydney Northern Beaches' },
  { name: 'The Basin NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'The Rocks NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'The University Of Sydney NSW', postcode: '2006', region: 'Sydney CBD' },
  { name: 'Thornleigh NSW', postcode: '2120', region: 'Northwest Sydney' },
  { name: 'Toongabbie East NSW', postcode: '2146', region: 'Sydney Western Suburbs' },
  { name: 'Turramurra NSW', postcode: '2074', region: 'Sydney North Shore' },
  { name: 'Turrella NSW', postcode: '2205', region: 'Sydney Inner West' },
  { name: 'Umina Beach NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Unsw Sydney NSW', postcode: '2052', region: 'Sydney Eastern Suburbs' },
  { name: 'Varroville NSW', postcode: '2566', region: 'Sydney Western Suburbs' },
  { name: 'Vaucluse NSW', postcode: '2030', region: 'Sydney Eastern Suburbs' },
  { name: 'Voyager Point NSW', postcode: '2172', region: 'Sydney Sutherland Shire' },
  { name: 'Wagstaffe NSW', postcode: '2257', region: 'Sydney Northern Beaches' },
  { name: 'Wahroonga NSW', postcode: '2076', region: 'Sydney North Shore' },
  { name: 'Waitara NSW', postcode: '2077', region: 'Sydney North Shore' },
  { name: 'Wakeley NSW', postcode: '2176', region: 'Sydney Western Suburbs' },
  { name: 'Wareemba NSW', postcode: '2046', region: 'Sydney Inner West' },
  { name: 'Warrawee NSW', postcode: '2074', region: 'Sydney North Shore' },
  { name: 'Warriewood NSW', postcode: '2102', region: 'Sydney Northern Beaches' },
  { name: 'Warringah Mall NSW', postcode: '2100', region: 'Sydney Northern Beaches' },
  { name: 'Warumbul NSW', postcode: '2229', region: 'Sydney Sutherland Shire' },
  { name: 'Watsons Bay NSW', postcode: '2030', region: 'Sydney Eastern Suburbs' },
  { name: 'Wattle Grove NSW', postcode: '2173', region: 'Sydney Western Suburbs' },
  { name: 'Wentworthville NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'West Hoxton NSW', postcode: '2171', region: 'Sydney Western Suburbs' },
  { name: 'West Pennant Hills NSW', postcode: '2125', region: 'Northwest Sydney' },
  { name: 'West Pymble NSW', postcode: '2073', region: 'Sydney North Shore' },
  { name: 'West Ryde NSW', postcode: '2114', region: 'Sydney North Shore' },
  { name: 'Westleigh NSW', postcode: '2120', region: 'Northwest Sydney' },
  { name: 'Wetherill Park NSW', postcode: '2164', region: 'Sydney Western Suburbs' },
  { name: 'Whalan NSW', postcode: '2770', region: 'Sydney Western Suburbs' },
  { name: 'Whale Beach NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Wheeler Heights NSW', postcode: '2097', region: 'Sydney Northern Beaches' },
  { name: 'Wiley Park NSW', postcode: '2195', region: 'Sydney Western Suburbs' },
  { name: 'Winston Hills NSW', postcode: '2153', region: 'Northwest Sydney' },
  { name: 'Wollstonecraft NSW', postcode: '2065', region: 'Sydney North Shore' },
  { name: 'Woodcroft NSW', postcode: '2767', region: 'Sydney Western Suburbs' },
  { name: 'Woodpark NSW', postcode: '2164', region: 'Sydney Western Suburbs' },
  { name: 'Woolooware NSW', postcode: '2230', region: 'Sydney Sutherland Shire' },
  { name: 'Woolwich NSW', postcode: '2110', region: 'Sydney North Shore' },
  { name: 'Woronora NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Woronora Dam NSW', postcode: '2232', region: 'Sydney Sutherland Shire' },
  { name: 'Woronora Heights NSW', postcode: '2233', region: 'Sydney Sutherland Shire' },
  { name: 'Yarrawarrah NSW', postcode: '2233', region: 'Sydney Sutherland Shire' },
  { name: 'Yowie Bay NSW', postcode: '2228', region: 'Sydney Sutherland Shire' },

  // Final missing suburbs from locations.md
  { name: 'Avalon Beach NSW', postcode: '2107', region: 'Sydney Northern Beaches' },
  { name: 'Chatswood West NSW', postcode: '2067', region: 'Sydney North Shore' },
  { name: 'Cogra Bay NSW', postcode: '2083', region: 'Sydney North Shore' },
  { name: 'Cremorne Junction NSW', postcode: '2090', region: 'Sydney North Shore' },
  { name: 'Cremorne Point NSW', postcode: '2090', region: 'Sydney North Shore' },
  { name: 'Greystanes NSW', postcode: '2145', region: 'Sydney Western Suburbs' },
  { name: 'Gymea Bay NSW', postcode: '2227', region: 'Sydney Sutherland Shire' },
  { name: 'Marrickville Metro NSW', postcode: '2204', region: 'Sydney Inner West' },
  { name: 'Marrickville South NSW', postcode: '2204', region: 'Sydney Inner West' },
  { name: 'Melrose Park NSW', postcode: '2114', region: 'Sydney North Shore' },
  { name: 'Minto Heights NSW', postcode: '2566', region: 'Sydney Western Suburbs' },
  { name: 'North Sydney Shoppingworld NSW', postcode: '2060', region: 'Sydney North Shore' },
  { name: 'St Clair NSW', postcode: '2759', region: 'Sydney Western Suburbs' },
  { name: 'St Leonards NSW', postcode: '2065', region: 'Sydney North Shore' },
  { name: 'Strawberry Hills NSW', postcode: '2012', region: 'Sydney Eastern Suburbs' },
  { name: 'Sydney NSW', postcode: '2000', region: 'Sydney CBD' },
  { name: 'Waterfall NSW', postcode: '2233', region: 'Sydney Sutherland Shire' },
  { name: 'Willoughby East NSW', postcode: '2068', region: 'Sydney North Shore' },
  { name: 'Willoughby North NSW', postcode: '2068', region: 'Sydney North Shore' },
  { name: 'Yagoona West NSW', postcode: '2199', region: 'Sydney Western Suburbs' },
];
